weather_project:
  outputs:
    dev:
      dbname: warehouse
      host: postgres
      pass: de
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: de
  target: dev
